INSERT INTO location
  (name, address, zip, city, url)
VALUES
  ('Online event', NULL, NULL, NULL, NULL),
  ('Talent Garden Austria', 'Liechtensteinstraße 111-115', 1090, 'Vienna', 'https://talentgarden.org/en/coworking/austria/vienna');
  -- ('address', zip, 'city', 'url'),

INSERT INTO organizer
  (name, description, location_id, contact, email, phone, url)
VALUES
  ('the female factor', 'The female factor is a curated global community advancing careers and creating business opportunities for a new era of female leaders by boosting confidence, competence & connections.<br>No matter your goal - whether you want to work towards that promotion, settle in a new environment, change professions, write that book, start your own business or just want to be surrounded by other kickass women - we have your back.<br>Our tailor-made opportunity journey is designed to get you ahead with the right mentors, hands-on career knowledge, confidence training and a great network of like-minded people from over 47 countries worldwide.', 2, 'Tanja Sternbauer', 'hi@femalefactor.global', NULL, 'https://www.femalefactor.global'),
  ('Talent Garden Austria', 'The Talent Garden Innovation School provides fast, in-depth, and hands-on training programs designed to meet the real needs of the job market. We offer courses in the fields of digital technologies and innovation, with a focus on coding, UX design, data analysis, and digital marketing. Our formats range from 2-day Masterclasses to 8-weeks part-time and 3-month full-time programs.', 2, NULL, 'vienna@talentgarden.at', '+4312058183', 'https://talentgarden.org/en/coworking/austria/vienna');
  -- ('name', 'description', fk_location, 'email', 'phone', 'url'),

INSERT INTO event 
  (name, type, date, start, end, lead, description, organizer_id, location_id, category, price, img, url)
VALUES
  ('challenges of a female leader | the female factor fireside chat', 'Masterclass', '2022-06-29', '17:00:00', '18:30:00', 'Stepping up as a leader comes with certain challenges, especially as a woman.', 'Learn what you will encounter on your way up and explore how to deal with it', 1, 1, 'Business, Career, Women, Leadership', 74.75, '213642869_521976634379.jpg', 'https://www.eventbrite.com/e/challenges-of-a-female-leader-the-female-factor-fireside-chat-tickets-249480080637'),
  ('crucial conversations | the female factor impulse talk', 'Impulse talk', '2022-04-12', '18:00:00', '19:30:00', 'Learn more about the basics of good communication and prepare yourself to lead crucial conversations confidently.', 'Think of a conversation you had that you couldn’t wait to end. The discomfort, confusion or other emotions you felt are probably hard to forget.<br>Every once in a while, be it in the workspace or in your life, you realise that you need to have a conversation that’s not necessarily easy to have for either party involved. You could beat around the bush or avoid having it altogether, and when you inevitably end up needing to have it, you may not know how to navigate it.<br>In times like these, crucial communication skills come to your aid - from listening, to speaking and everything in between, we’re tackling it all in our online event.<br>the female factor would like to invite you to a discussion about communication skills that can make or break you as a leader.', 1, 1, 'Business, Career, Women, Communication', 74.75, '249587609_521976634379.jpg', 'https://www.eventbrite.com/e/crucial-conversations-the-female-factor-impulse-talk-tickets-249443350777'),
  ('How to start a career in Digital Product Management?', 'Webinar', '2022-04-26', '18:00:00', '19:00:00', 'With Katia Cassano, Product Credit EMEA Lead at Paypal, Mentor', 'Are you interested in pivoting your career into Digital Product Management but you are unsure about where to start? This webinar is perfect for you!', 2, 1, 'Career, IT, Management', 0.00, '263139599_422416487889.jpg', 'https://www.eventbrite.com/e/how-to-start-a-career-in-digital-product-management-tickets-311822358067'),
  ('the work place of the future - what really matters to the next generation', 'Webinar', '2022-04-20', '17:30:00', '19:30:00', 'A large-scale study reveals insights on what the next generation really want from their workplaces and gives hands-on recommendations.', 'Foosball table, fruit basket, an in-house gym - you guessed it, these “woke benefits” won’t attract talent in the long run.<br>A new generation of leaders is on the horizon, and they are clearly setting a new standard when it comes to workplace expectations. We at the female factor partnered with EY to find out what the next generation of female professionals really want from their employers.', 1, 1, 'Business, Career, Women, Leadership', 0.00, '252968239_521976634379.jpg', 'https://www.eventbrite.com/e/the-work-place-of-the-future-what-really-matters-to-the-next-generation-tickets-304734989557'),
  ('leadership fair - the career event for future leaders', 'Career fair', '2022-05-31', '15:00:00', '18:00:00', 'What does it take to step up as a leader? And is it the right step for you?', 'Our leadership career fair will take you on your very own discovery journey to explore the different key traits of leadership through inspiring panels and hands-on workshops with real-life cases.<br>250+ aspiring leaders | 50+ pioneering companies | 25+ key leadership traits to develop<br><i>"If your actions inspire others to dream more, learn more, do more and become more, you are a leader.</i>"', 1, 1, 'Business, Career, Women, Leadership', 0.00, '261571269_521976634379.jpg', 'https://www.eventbrite.com/e/leadership-fair-the-career-event-for-future-leaders-tickets-249459599377');
  -- ('name', 'type', '2022--', ':00:00', ':00:00', 'lead', 'description', fk_location, fk_organizer, ['category'], price, 'img', 'url'),
  